### ISSUE TITLE
toasty tile-wwtl does not accept "--name=_____" as a modifier

### ISSUE THREAD

**Issue by astrodavid10** [WorldWideTelescope/toasty#53]
The command "toasty tile-wwtl" will not allow for the modifier "--name=_____" unlike "toasty tile-study" and as a result, the name must be added manually before the result is functional on the web, which includes the inability to use "wwtdatatool preview".

**Comment by pkgw** [comment]
This ought to be an easy fix — submitted in pull request #54.

**Comment by pkgw** [comment]
OK, I've added this feature in the 0.8.0 release which just went out.
