### ISSUE TITLE
tile-wwtl writes a local file path in index_rel.wtml and not a relative directory tree

### ISSUE THREAD

**Issue by astrodavid10** [WorldWideTelescope/toasty#56]
The function tile-wwtl writes a local file path to the resulting index_rel.wtml and not a relative directory tree. This breaks the preview function.

I looked into the code a bit and I'm not yet sure where this gets written, but am happy to fix if there are suggestions of where to poke further.

i.e. - Should be Url="{1}/{3}/{3}_{2}.png"

**Comment by pkgw** [comment]
Do you have an example WWTL file that causes this? If the URL field has a bad path, I'm not quite sure how that would happen.

**Comment by astrodavid10** [comment]
[3C196.zip](https://github.com/WorldWideTelescope/toasty/files/7125536/3C196.zip)
Here's an example with the example image.
[3C_196.zip](https://github.com/WorldWideTelescope/toasty/files/7125539/3C_196.zip)

**Comment by pkgw** [comment]
OK, I think I've fixed this. I'll issue a new release of toasty soon.
