### ISSUE TITLE
toasty pipeline AVM handling no longer accurate

### ISSUE THREAD

**Issue by astrodavid10** [WorldWideTelescope/toasty#65]
The latest release of toasty seems to have broken the ability for the toasty pipeline utility to correctly pull orientation from the metadata. See the example of https://noirlab.edu/public/images/noao-sh2-112/ where this first image is the processed result after the latest release 0.11.0 
<img width="1592" alt="b" src="https://user-images.githubusercontent.com/65675418/138639420-27bca41a-5c94-4e33-83d8-05e0bb97081f.png">

and the second image is from the prior release 0.10.0.
![a](https://user-images.githubusercontent.com/65675418/138639422-c6f2ea42-40cb-4920-911d-859b49c921f0.png)

**Comment by pkgw** [comment]
Figured it out — we had a bug in the processing here that was masked by the bug in the Y offset that I recently fixed. Fix incoming.

**Comment by pkgw** [comment]
I am just issuing version 0.12.0 of toasty, which should fix this.
